import type { Metadata } from "next";
import "./theme-config.css";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import { LayoutProps } from "@/model/props";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({ children, modal }: LayoutProps) {
    return (
        <html lang='en'>
            <body className={inter.variable}>
                <QueryClientProvider>
                    <AuthProvider>
                        <Theme appearance='light' accentColor='violet' scaling='110%'>
                            <NavBar />
                            <main className='p-5'>
                                <Container>
                                    {modal}
                                    {children}
                                </Container>
                            </main>
                        </Theme>
                    </AuthProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
